# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/accm/accm.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
# IP: The module: 'c_addsub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/accm/accm.gen/sources_1/ip/c_addsub_0/c_addsub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/accm/accm.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
# IP: The module: 'c_addsub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/accm/accm.gen/sources_1/ip/c_addsub_0/c_addsub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
