# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.srcs/sources_1/ip/LUT_1/LUT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.srcs/sources_1/ip/rgb2ycbcr_0_4/rgb2ycbcr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.gen/sources_1/ip/rgb2ycbcr_0_4/src/Multiplier/Multiplier.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Multiplier || ORIG_REF_NAME==Multiplier} -quiet] -quiet

# IP: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.gen/sources_1/ip/rgb2ycbcr_0_4/src/Adder/Adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder || ORIG_REF_NAME==Adder} -quiet] -quiet

# XDC: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.gen/sources_1/ip/LUT_1/LUT_ooc.xdc

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vp_0_0/hdmi_vga_vp_0_0.xci
# IP: The module: 'hdmi_vga_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.srcs/sources_1/ip/LUT_1/LUT.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LUT || ORIG_REF_NAME==LUT} -quiet] -quiet

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.srcs/sources_1/ip/rgb2ycbcr_0_4/rgb2ycbcr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0} -quiet] -quiet

# IP: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.gen/sources_1/ip/rgb2ycbcr_0_4/src/Multiplier/Multiplier.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Multiplier || ORIG_REF_NAME==Multiplier} -quiet] -quiet

# IP: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.gen/sources_1/ip/rgb2ycbcr_0_4/src/Adder/Adder.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder || ORIG_REF_NAME==Adder} -quiet] -quiet

# XDC: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/test/test.gen/sources_1/ip/LUT_1/LUT_ooc.xdc
