# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/Adder/Adder.xci
# IP: The module: 'Adder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/rgb2ycbcr/rgb2ycbcr.gen/sources_1/ip/Adder/Adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adder'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/Adder/Adder.xci
# IP: The module: 'Adder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/rgb2ycbcr/rgb2ycbcr.gen/sources_1/ip/Adder/Adder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adder'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
