# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/complex_module/complex_module.srcs/sources_1/ip/adder3/adder3.xci
# IP: The module: 'adder3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/complex_module/complex_module.gen/sources_1/ip/adder3/adder3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/complex_module/complex_module.srcs/sources_1/ip/adder3/adder3.xci
# IP: The module: 'adder3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karol/Documents/studia/sem6/reconfigurable-systems/lab4/complex_module/complex_module.gen/sources_1/ip/adder3/adder3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
