# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/wip/wip.srcs/sources_1/ip/add_22_22/add_22_22.xci
# IP: The module: 'add_22_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/wip/wip.gen/sources_1/ip/add_22_22/add_22_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_22_22'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/wip/wip.srcs/sources_1/ip/add_22_22/add_22_22.xci
# IP: The module: 'add_22_22' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Documents/studia/sem6/reconfigurable-systems/visual_track/wip/wip.gen/sources_1/ip/add_22_22/add_22_22_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_22_22'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
